# Testing pre andpost-synaptic rule
This notebook is meant as function test for the learning rules

In [14]:
def pre_synaptic_simple(epsilon, w, z_post, z_pre):
    increase = np.zeros_like(w)
    
    n = w.shape[0]
    for i in range(n):
        for j in range(n):
            increase[i, j] = z_pre[j] * z_post[i] - z_pre[j] * w[i, j]
    
    return epsilon * increase

def post_synaptic_simple(epsilon, w, z_post, z_pre):
    increase = np.zeros_like(w)
    
    n = w.shape[0]
    for i in range(n):
        for j in range(n):
            increase[i, j] = z_post[i] * z_pre[j] - z_post[i] * w[i, j]
            
    return epsilon * increase

def pre_synaptic(epsilon, w, z_post, z_pre):
    
    return epsilon * (np.outer(z_post, z_pre) - w * z_pre)

def post_synaptic(epsilon, w, z_post, z_pre):

    return epsilon * (np.outer(z_pre, z_post) - z_post * w).T

## Post-synaptic

In [15]:
dimension = 3
z_pre = np.ones(dimension)
w = np.zeros((dimension, dimension))
z_post = np.ones(dimension)
epsilon = 0.5

aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
aux2 = post_synaptic(epsilon, w, z_post, z_pre)

print('aux1', aux1)
print('aux2', aux2)

aux1 [[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]
aux2 [[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]


In [16]:
dimension = 3
z_pre = np.ones(dimension)
w = np.zeros((dimension, dimension))
z_post = np.zeros(dimension)
epsilon = 0.5

aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
aux2 = post_synaptic(epsilon, w, z_post, z_pre)

print('aux1', aux1)
print('aux2', aux2)

aux1 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
aux2 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [17]:
dimension = 3
z_pre = np.zeros(dimension)
z_pre[0] = 1
w = np.zeros((dimension, dimension))
z_post = np.zeros(dimension)
z_post[1] = 1
epsilon = 0.5

aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
aux2 = post_synaptic(epsilon, w, z_post, z_pre)

print('aux1', aux1)
print('aux2', aux2)

aux1 [[ 0.   0.   0. ]
 [ 0.5  0.   0. ]
 [ 0.   0.   0. ]]
aux2 [[ 0.   0.   0. ]
 [ 0.5  0.   0. ]
 [ 0.   0.   0. ]]


In [18]:
dimension = 3
z_pre = np.zeros(dimension)
z_pre[0] = 1
w = np.zeros((dimension, dimension))
z_post = np.zeros(dimension)
z_post[2] = 1
epsilon = 0.5

aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
aux2 = post_synaptic(epsilon, w, z_post, z_pre)

print('aux1', aux1)
print('aux2', aux2)

aux1 [[ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 0.5  0.   0. ]]
aux2 [[ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 0.5  0.   0. ]]


In [29]:
dimension = 10
index_1 = np.random.randint(0, dimension)
index_2 = np.random.randint(0, dimension)

z_pre = np.zeros(dimension)
z_pre[index_1] = 1
w = np.zeros((dimension, dimension))
z_post = np.zeros(dimension)
z_post[index_2] = 1
epsilon = 0.5

aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
aux2 = post_synaptic(epsilon, w, z_post, z_pre)

print('aux1', aux1)
print('aux2', aux2)
np.sum(aux1 - aux2)

aux1 [[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]
aux2 [[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.

0.0

Let's test it systematically

In [31]:
errors = []
for i in range(100):
    dimension = 10
    index_1 = np.random.randint(0, dimension)
    index_2 = np.random.randint(0, dimension)

    z_pre = np.zeros(dimension)
    z_pre[index_1] = 1
    w = np.zeros((dimension, dimension))
    z_post = np.zeros(dimension)
    z_post[index_2] = 1
    epsilon = 0.5

    aux1 = post_synaptic_simple(epsilon, w, z_post, z_pre)
    aux2 = post_synaptic(epsilon, w, z_post, z_pre)

    errors.append(np.sum(aux1 - aux2))

np.sum(errors)
    

0.0

## Test the pre-synaptic rule

In [32]:
errors = []
for i in range(100):
    dimension = 10
    index_1 = np.random.randint(0, dimension)
    index_2 = np.random.randint(0, dimension)

    z_pre = np.zeros(dimension)
    z_pre[index_1] = 1
    w = np.zeros((dimension, dimension))
    z_post = np.zeros(dimension)
    z_post[index_2] = 1
    epsilon = 0.5

    aux1 = pre_synaptic_simple(epsilon, w, z_post, z_pre)
    aux2 = pre_synaptic(epsilon, w, z_post, z_pre)

    errors.append(np.sum(aux1 - aux2))

np.sum(errors)
    

0.0